# Main colors
background            #0e1514
foreground            #dde4e2
cursor                #dde4e2
cursor_text_color     #0e1514
selection_background  #324b48
selection_foreground  #cce8e3
url_color             #aec9e6

# ANSI colors
color0                #0e1514
color1                #ffb4ab
color2                #aec9e6
color3                #b1ccc7
color4                #81d5cb
color5                #aec9e6
color6                #b1ccc7
color7                #dde4e2
color8                #3f4947
color9                #93000a
color10               #2e4961
color11               #324b48
color12               #00504a
color13               #324b48
color14               #2e4961
color15               #bec9c6

# Starship prompt bubbles
color255              #00504a
color254              #81d5cb
color253              #324b48
color252              #b1ccc7
color251              #2e4961
color250              #aec9e6
color249              #93000a
color248              #ffb4ab
color232              #9df2e7
color233              #003733
color234              #cce8e3
color235              #1c3532
color236              #cde5ff
color237              #163349
color238              #ffdad6
color239              #690005
color240              #9df2e7
color243              #81d5cb
color244              #ffb4ab
color245              #3f4947

# UI elements
active_tab_foreground   #003733
active_tab_background   #81d5cb
inactive_tab_foreground #9df2e7
inactive_tab_background #00504a
active_border_color     #81d5cb
inactive_border_color   #899391

# Marks
mark1_foreground        #00201d
mark1_background        #9df2e7
mark2_foreground        #051f1d
mark2_background        #cce8e3
mark3_foreground        #001d32
mark3_background        #cde5ff
