# 音乐目录和数据库设置
music_directory    "/home/xingjian/Music"
playlist_directory "/home/xingjian/.config/mpd/playlists"
db_file            "/home/xingjian/.config/mpd/database"
log_file           "/home/xingjian/.config/mpd/log"
pid_file           "/home/xingjian/.config/mpd/pid"
state_file         "/home/xingjian/.config/mpd/state"

# 建议添加自动更新，这样你往 Music 文件夹丢歌时不用手动按 u
auto_update        "yes"
# 监听设置
bind_to_address    "127.0.0.1"
port               "6600"

# 音频输出 (PulseAudio/PipeWire 通用)
audio_output {
    type            "pulse"
    name            "PulseAudio"
    # 强制指定软件混音，避免 n/a 音量错误
    mixer_type      "software"
}

# 可视化频谱数据源 (为 ncmpcpp 准备)
audio_output {
    type            "fifo"
    name            "Visualizer feed"
    path            "/tmp/mpd.fifo"
    format          "44100:16:2"
}
