-- return {
--   -- 自动补全（增强版）
--   {
--     "hrsh7th/nvim-cmp",
--     event = "InsertEnter", -- ❗ 延迟加载
--     dependencies = {
--       "hrsh7th/cmp-nvim-lsp",
--       "hrsh7th/cmp-buffer",
--       "hrsh7th/cmp-path",
--       "L3MON4D3/LuaSnip",
--       "saadparwaiz1/cmp_luasnip",
--       "onsails/lspkind-nvim",
--       "rafamadriz/friendly-snippets",
--       "hrsh7th/cmp-cmdline",
--       "hrsh7th/cmp-buffer",
--     },
--     config = function()
--       local cmp = require("cmp")
--       local luasnip = require("luasnip")
--       local lspkind = require("lspkind")
--
--       require("luasnip.loaders.from_vscode").lazy_load()
--
--       -- ✅ 关键：让 cpp 文件也能用 c 片段
--       luasnip.filetype_extend("cpp", { "c" })
--
--       -- ====== 🧩 主补全配置 ======
--       cmp.setup({
--         snippet = {
--           expand = function(args)
--             luasnip.lsp_expand(args.body)
--           end,
--         },
--         mapping = cmp.mapping.preset.insert({
--           ["<C-n>"] = cmp.mapping.select_next_item(),
--           ["<C-p>"] = cmp.mapping.select_prev_item(),
--           ["<CR>"] = cmp.mapping.confirm({ select = true }),
--           ["<C-Space>"] = cmp.mapping.complete(),
--           -- ❌ ESC：如果补全菜单开启则关闭，否则执行正常 ESC
--           ["<Esc>"] = cmp.mapping(function(fallback)
--             if cmp.visible() then
--               cmp.abort()
--             else
--               fallback()
--             end
--           end, { "i", "s" }),
--           ["<Tab>"] = cmp.mapping(function(fallback)
--             if cmp.visible() then
--               cmp.select_next_item()
--             elseif luasnip.expand_or_jumpable() then
--               luasnip.expand_or_jump()
--             else
--               fallback()
--             end
--           end, { "i", "s" }),
--           ["<S-Tab>"] = cmp.mapping(function(fallback)
--             if cmp.visible() then
--               cmp.select_prev_item()
--             elseif luasnip.jumpable(-1) then
--               luasnip.jump(-1)
--             else
--               fallback()
--             end
--           end, { "i", "s" }),
--         }),
--         window = {
--           completion = cmp.config.window.bordered({
--             border = "rounded",
--             scrollbar = false, -- 🚫 禁用滚动条
--             winhighlight = "NormalFloat:Pmenu,FloatBorder:FloatBorder,Pmenu:Pmenu,CursorLine:PmenuSel",
--           }),
--           documentation = cmp.config.window.bordered({
--             border = "rounded",
--             scrollbar = false, -- 🚫 禁用滚动条
--             winhighlight = "NormalFloat:Pmenu,FloatBorder:FloatBorder,Pmenu:Pmenu,PmenuSel:PmenuSel",
--           }),
--         },
--         formatting = {
--           fields = { "kind", "abbr", "menu" },
--           format = function(entry, vim_item)
--             vim_item.kind = lspkind.symbolic(vim_item.kind, { mode = "symbol_text" })
--             vim_item.menu = ({
--               nvim_lsp = "[LSP]",
--               luasnip = "[Snip]",
--               buffer = "[Buf]",
--               path = "[Path]",
--             })[entry.source.name]
--             return vim_item
--           end,
--         },
--         -- experimental = {
--         -- 	ghost_text = true,
--         -- },
--         sources = cmp.config.sources({
--           { name = "nvim_lsp" },
--           { name = "luasnip" },
--           { name = "buffer" },
--           { name = "path" },
--         }),
--       })
--       -- ====== ⚙️ 命令行模式补全 ======
--       cmp.setup.cmdline(":", {
--         mapping = cmp.mapping.preset.cmdline(),
--         sources = cmp.config.sources({
--           { name = "path" },
--           { name = "cmdline" },
--         }),
--       })
--
--       -- ====== 🔍 搜索模式补全 ======
--       cmp.setup.cmdline("/", {
--         mapping = cmp.mapping.preset.cmdline(),
--         sources = {
--           { name = "buffer" },
--         },
--       })
--     end,
--   },
-- }

return {}
