-- return {
--   "nvim-tree/nvim-tree.lua",
--   dependencies = { "nvim-tree/nvim-web-devicons" },
--   config = function()
--     local nvim_tree = require("nvim-tree")
--     nvim_tree.setup({
--       sort_by = "name",
--       view = {
--         width = function()
--           return math.floor(vim.o.columns * 0.15)
--         end,
--         side = "left",
--       },
--       renderer = { icons = { show = { git = true, folder = true, file = true, folder_arrow = true } } },
--       git = { enable = true, ignore = true },
--       filters = { custom = { "*.o", "*.out", "a.out" }, dotfiles = false, exclude = {} },
--       actions = { open_file = { quit_on_open = false } },
--
--       -- 功能增强
--       update_focused_file = { enable = true, update_cwd = true },
--       sync_root_with_cwd = true,
--       reload_on_bufenter = true,
--     })
--   end,
-- }

return {}
