# foot.ini

[main]
font=Maple Mono NF:size=13, Source Han Sans CN:size=13, Noto Color Emoji:size=13
# initial-window-size-chars=100x30
resize-delay-ms=0
pad=2x2                                # 窗口内边距，类似 Kitty
vertical-letter-offset=1               # 微调行高
selection-target=both

[environment]
# 这里保持默认即可
[scrollback]
lines=10000                            # 调大滚动行数
[cursor]
style=block
blink=yes
blink-rate=500                         # 显式指定闪烁频率（毫秒）

[mouse]
hide-when-typing=yes

[colors-dark]
alpha=1
# Catppuccin Macchiato 基础前背景色
background=24273a
foreground=cad3f5

# Catppuccin Macchiato 调色板
regular0=494d64  # surface1
regular1=ed8796  # red
regular2=a6da95  # green
regular3=eed49f  # yellow
regular4=8aadf4  # blue
regular5=f5bde6  # pink
regular6=8bd5ca  # teal
regular7=b8c0e0  # subtext1

bright0=5b6078   # surface2
bright1=ed8796   # bright red
bright2=a6da95   # bright green
bright3=eed49f   # bright yellow
bright4=8aadf4   # bright blue
bright5=f5bde6   # bright pink
bright6=8bd5ca   # bright teal
bright7=a5adce   # subtext0

# 光标颜色：前景色 背景色 (Macchiato Base 和 Rosewater)
cursor=24273a f4dbd6

[csd]
preferred=server                       # 隐藏自带标题栏
